sudo: required

language: go

go:
  - 1.13.1

services:
  - docker

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12-postgis-3

# trying to fix postgis bug which comes on the travis infrastructure that has sudo.
before_install:
  - docker --version
  - export DEBIAN_FRONTEND=noninteractive;
  - export PATH=$PATH:$HOME/.local/bin
  - export GOFLAGS=-mod=vendor

install:
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log;
  - sudo apt-get install -y xsltproc
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
  - sudo systemctl restart postgresql@12-main
  - psql -U postgres -c "create extension postgis"
  - ./etc/scripts/initdb.sh
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
  - pip install --user awscli
  - eval $(aws ecr get-login --no-include-email --region ap-southeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars

stages:
  - test
  - build

jobs:
  include:
  - stage: test
    script:
      - make -C vendor/github.com/GeoNet/kit/cvendor/libmseed
      - make -C vendor/github.com/GeoNet/kit/cvendor/libslink
      - test -z "$(gofmt -s -l `find . -name "*.go" | egrep -v vendor` | tee /dev/stderr)"
      - go vet ./...
      - go test -v ./internal/...
      - ./all.sh
      - 'if [ "TRAVIS_SECURE_ENV_VARS" = "true" ]; then bash ./all-integration.sh; fi'
      - golangci-lint run -E gosec # default linters + gosec
  - stage: build
    script:
      - >-
        bash build.sh
        fdsn-quake-consumer
        fdsn-ws-nrt
    env: DOCKERFILE=Dockerfile.tmplate
    deploy:
      - provider: script
        script: >-
          bash push.sh
        on_branch: main

  - stage: build
    script:
      - >-
        bash build.sh
        fdsn-ws
        fdsn-holdings-consumer
        fdsn-slink-db
    env: DOCKERFILE=Dockerfile.cgo
    deploy:
      - provider: script
        script: >-
          baash push.sh
          fdsn-ws
          fdsn-holdings-consumer
          fdsn-slink-db
        on_branch: main
 
notifications:
  email: false
  slack:
    if: branch in (main, staging, production)
    on_success: never
    on_failure: always
    on_pull_requests: false
    secure: ORAvJSxRCtRUhc6oca4LaWg1ZDoau1ylBawVNRCj5aN2sTc6SYTDgQmk1vguyuRMZqg2OUVinpNxBtxpol0mhzqcnuR6hg74syWL1CJaLR6zzZQZrdMq5PhzudeJ/ScoJeMF4puExD7oh03NyY76xSDjP1PSOTE1XetGlXE/OSmr7bATiwgVQn9Qo+lxJWRgVNOUUcCPxjaXbKMrMMQupuFR1pvViI7U8ShQETQ1Vq9dqQxlStG2KpijGmQtYgSdJw2zFSS5XPnba2ju7HBMq6IBP5zOhXmUSl1NRsDnP0Tj91ndPkUJeG2toIF15I5Ajxp+JbfIBLkuUNXd0Qp+DpGmfMKWPFf4gsKDtaqN78WR9eMqHbXxNFhbPMIFSaD7gYAhcEYSVq5CbaOtQflU6Sg0tADLIws91Vsdh+KzQifmKOgkf7YBiCUCm3zbO665lDSUl7UjVl8XDb/pf4Nrl6C3pvxaNVCeq+Xcf3s3BwknfvL7MB8wQTkn6Nkhim8JuQGsT69TzDkvzr12skBcPo+zlnYsqQ4Hc5bzM5Sq+BzQMq6dnQpUazstaaPQhbcttyacIWWzlvD4iGOhCUqtfFNkk2AYNgO4DuR6chojbdrwhoRFrFmR1a4rXjDNyYT3EPxTVOZ6QrpgYyx0xNvaUWRI8bkfYNiheT/rNEiCpxo=
